name: Gradle

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make allure-results dir
        run: mkdir -p build/allure-results
      - name: Set up allurectl
        uses: baev/allurectl-setup@main
        with:
          version: 1.16.5
      - name: Allure TestOps Integration
        uses: baev/action-allure-testops@main
        env:
          ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_PROJECT_ID: 29
      - name: Build with Gradle
        run: ./gradlew build
      - name: List allure-results
        run: ls -d -1 "$PWD/"build/allure-results/*

